# Generated by Django 3.0.7 on 2020-09-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='scraper',
            name='currency',
            field=models.CharField(default='N/D', max_length=115, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='scraper',
            name='frequency',
            field=models.IntegerField(default=0, verbose_name='Frecuencia'),
        ),
    ]
