# Generated by Django 3.0.7 on 2020-09-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200902_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Creación'),
        ),
    ]
