# Generated by Django 3.0.7 on 2020-09-02 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200902_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 2, 15, 37, 48, 783575)),
            preserve_default=False,
        ),
    ]
