# Generated by Django 3.0.7 on 2020-09-02 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200902_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 2, 17, 39, 53, 260710)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scraper',
            name='currency',
            field=models.CharField(default='N/D', max_length=115, unique=True, verbose_name='Moneda'),
        ),
    ]
